name: databricks-env

dependencies:
  - ipython=7.31.1
  - matplotlib=3.5.2
  - pip=22.2.2
  - python=3.9.13
  - scikit-learn=1.0.2
  - numpy=1.21.5
  - pandas=1.4.4
  - selenium-4.8.0
  - bs4-0.0.1
  - requests-2.28.2
  - matplotlib-3.5.2
